# Generated by Django 2.1.5 on 2019-06-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travelogue', '0003_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='Somewhere Mysterious', max_length=30),
        ),
    ]
