# Generated by Django 2.1.5 on 2019-06-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travelogue', '0004_auto_20190618_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
